[[Clients]]
enable = true # 是否启用
cmd = "ssh -p ***** root@*****" # 粘贴ssh登录指令
password = "*******" # 粘贴ssh登录密码
ports = ["6006", "11451"]

# 填写需要映射的端口，可以是多个，支持映射到本地的不同端口。
# 比如填写 "6006"，则会映射到本地的6006端口，
# 填写 "1234:5678"，则会将远程的1234端口映射到本地的5678端口。